### ISSUE TITLE
The application don't compile for higher versions than JAVA8

### ISSUE THREAD

**Issue by tomstevns** [spring-petclinic/spring-framework-petclinic#3]
The application don't compile for higher versions than JAVA8

Med venlig hilsen / Kind regards

Tom Stevns
Adjunkt / Assistant profressor - Computer Science

KEA – Københavns Erhvervsakademi
Copenhagen School of Design and Technology
Lygten 37
DK 2400 København NV

**Comment by arey** [comment]
There is another problem with wro4j:

> [ERROR] Failed to execute goal ro.isdc.wro4j:wro4j-maven-plugin:1.8.0:run (default) on project spring-petclinic: Execution default of goal ro.isdc.wro4j:wro4j-maven-plugin:1.8.0:run failed: An API incompatibility was encountered while executing ro.isdc.wro4j:wro4j-maven-plugin:1.8.0:run: java.lang.ExceptionInInitializerError: null

**Comment by tomstevns** [comment]
Hi Antoine,

I will return the complete compiler stack trace to You tomorrow.

 Best regards

Tom Stevns
Ass. prof. At KEA In CPH/DK

søn. 15. apr. 2018 kl. 18.34 skrev Antoine Rey <notifications@github.com>:

**Comment by arey** [comment]
My last commit https://github.com/spring-petclinic/spring-framework-petclinic/commit/2562194fa624587e9f4462b29ce0d32a6daf23b8 should fix this issue. Please could you test it?

**Comment by arey** [comment]
Please reopen this issue if the problem persists.

**Comment by VovaRipetsky** [comment]
Still can't build war:

ERROR] Failed to execute goal on project spring-framework-petclinic: Could not resolve dependencies for project org.springframework.samples:spring-framework-petclinic:war:5.2.3: Failed to collect dependencies at org.springframework.data:spring-data-jdbc-core:jar:2.0.0.M1: Failed to read artifact descriptor for org.springframework.data:spring-data-jdbc-core:jar:2.0.0.M1: Could not transfer artifact org.springframework.data:spring-data-jdbc-core:pom:2.0.0.M1 from/to repository.spring.milestone (http://repo.spring.io/milestone): Access denied to: http://repo.spring.io/milestone/org/springframework/data/spring-data-jdbc-core/2.0.0.M1/spring-data-jdbc-core-2.0.0.M1.pom , ReasonPhrase:Forbidden. -> [Help 1]

**Comment by VovaRipetsky** [comment]
Need to change 
<spring-data-jdbc.version>2.0.0.M1</spring-data-jdbc.version> in pom

**Comment by arey** [comment]
I've just removed the `spring-data-jdbc-core` dependency (cf. commit https://github.com/spring-petclinic/spring-framework-petclinic/commit/ea0f7c63174c2f73b60188f74316f23a42355d3a) 
Could you please retry?

**Comment by arey** [comment]
I consider it's working. Please reopen this issue if it's not?

**Comment by sampada-gupta** [comment]
@Arey,
I am still getting the same error :
Failed to execute goal on project spring-framework-petclinic: Could not resolve dependencies for project org.springframework.samples:spring-framework-petclinic:war:5.1.3: Failed to collect dependencies at org.springframework.data:spring-data-jdbc-core:jar:2.0.0.M1: Failed to read artifact descriptor for org.springframework.data:spring-data-jdbc-core:jar:2.0.0.M1: Could not transfer artifact org.springframework.data:spring-data-jdbc-core:pom:2.0.0.M1 from/to repository.spring.milestone (http://repo.spring.io/milestone): Authorization failed for http://repo.spring.io/milestone/org/springframework/data/spring-data-jdbc-core/2.0.0.M1/spring-data-jdbc-core-2.0.0.M1.pom 403 Forbidden -> [Help 1]
Please suggest.

**Comment by sampada-gupta** [comment]
The issue got resolved after adding below dependency in POM.xml file:
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-jdbc-core</artifactId>
    <version>1.0.0.RELEASE</version>
</dependency>

Thanks

**Comment by arey** [comment]
`spring-data-jdbc-core` has been removed. Please `git fetch` the repo.

**Comment by cheelvis** [comment]
Im having some problem deploying my artifacts to nexus i keep getting the error "Could not transfer artifact org.springframework.samples:spring-petclinic:war:1.0.0 from/to " Any idea on how to go about that?

**Comment by kumarrajesh579** [comment]
> The issue got resolved after adding below dependency in POM.xml file:
> 
> org.springframework.data
> spring-data-jdbc-core
> 1.0.0.RELEASE
> Thanks

Hi, 
Could you please send in the updated pom.xml
Am getting error while trying to build the war.
